#!/usr/bin/env python3
"""Author-time helper: emit a `world.usda` link hierarchy from a URDF.

Given a URDF file, this script writes a USDA scene file containing one
``Xform`` prim per URDF link, tagged with
``customData = { string mimeNodeName = "arm_link_<urdf_name>" }`` so
the MIME runner can route the corresponding actor's pose state to the
right prim.

Mesh data is NOT emitted — the prims are placeholder Xforms. Add mesh
references by hand (or extend this helper) once you've decided where
the visual STLs live.

Usage::

    python scripts/urdf_to_usd_scene.py \
        path/to/robot.urdf \
        --output path/to/scene/world.usda \
        [--vessel-radius 0.0047 --vessel-length 0.02]

This tool is intentionally dependency-light: it only uses the Python
standard library (xml.etree). No JAX, no MADDENING, no MIME imports.
"""

from __future__ import annotations

import argparse
import os
import sys
import xml.etree.ElementTree as ET
from typing import List


# ---------------------------------------------------------------------------
# URDF parsing — names only (we don't need joint axes or inertials here).
# ---------------------------------------------------------------------------


def _parse_link_names(urdf_path: str) -> List[str]:
    """Return the URDF's link names in document order.

    We tolerate URDFs that include world/base fixed joints — every
    `<link>` element in the file produces an Xform in the output, in
    the order they appear.
    """
    tree = ET.parse(urdf_path)
    root = tree.getroot()
    if root.tag != "robot":
        raise ValueError(
            f"Expected <robot> root in {urdf_path}, got <{root.tag}>"
        )
    names: List[str] = []
    for link_el in root.findall("link"):
        name = link_el.get("name")
        if name is None:
            continue
        names.append(name)
    if not names:
        raise ValueError(f"URDF {urdf_path} contains no <link> elements")
    return names


# ---------------------------------------------------------------------------
# USDA emission
# ---------------------------------------------------------------------------


def _sanitize_prim_name(link_name: str) -> str:
    """Turn an arbitrary URDF link name into a valid USD prim name.

    USD prim names must match `[A-Za-z_][A-Za-z0-9_]*`. We CamelCase
    snake_case names so the human-readable URDF naming convention
    survives the mapping (`base_link` -> `BaseLink`, `link_1` ->
    `Link1`).
    """
    parts = [p for p in link_name.replace("-", "_").split("_") if p]
    out = "".join(p[:1].upper() + p[1:] for p in parts)
    if not out:
        out = "Link"
    if not (out[0].isalpha() or out[0] == "_"):
        out = "L" + out
    return out


def _emit_link_xform(prim_name: str, mime_node_name: str, indent: str = "        ") -> str:
    """Return the USDA snippet for one Xform prim."""
    return (
        f'{indent}def Xform "{prim_name}" (\n'
        f'{indent}    customData = {{\n'
        f'{indent}        string mimeNodeName = "{mime_node_name}"\n'
        f'{indent}    }}\n'
        f'{indent})\n'
        f'{indent}{{\n'
        f'{indent}    double3 xformOp:translate = (0, 0, 0)\n'
        f'{indent}    quatd xformOp:orient = (1, 0, 0, 0)\n'
        f'{indent}    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:orient"]\n'
        f'{indent}}}\n'
    )


def emit_usda(
    link_names: List[str],
    *,
    vessel_radius_m: float = 0.0047,
    vessel_length_m: float = 0.02,
    arm_actor_prefix: str = "arm_link_",
) -> str:
    """Build a USDA string for the given URDF link list.

    Parameters
    ----------
    link_names : list[str]
        URDF link names in document order.
    vessel_radius_m, vessel_length_m : float
        Default vessel geometry (cylinder along Z). Override for
        non-cylindrical / different-sized environments.
    arm_actor_prefix : str
        Prefix used to construct each link's `mimeNodeName`. The
        runner uses this to find the matching actor in
        `experiment.yaml`. The default `arm_link_` matches the
        convention used by the `_template_helical_drive` and
        `ar4_helical_drive` experiments.
    """
    # Header
    lines: List[str] = []
    lines.append('#usda 1.0')
    lines.append('(')
    lines.append('    defaultPrim = "World"')
    lines.append('    metersPerUnit = 1.0')
    lines.append('    upAxis = "Z"')
    lines.append('    doc = """Auto-generated by scripts/urdf_to_usd_scene.py.')
    lines.append('    Each Xform under /World/Actors/Arm corresponds to one URDF link.')
    lines.append('    Replace this file with a hand-authored USDA if you want to attach')
    lines.append('    visual meshes or override the prim hierarchy."""')
    lines.append(')')
    lines.append('')
    lines.append('def Xform "World"')
    lines.append('{')
    lines.append('    def Scope "Actors"')
    lines.append('    {')
    lines.append('        def Xform "Arm"')
    lines.append('        {')

    for link in link_names:
        prim_name = _sanitize_prim_name(link)
        mime_name = f"{arm_actor_prefix}{link}"
        # _emit_link_xform already terminates with newline.
        lines.append(_emit_link_xform(prim_name, mime_name, indent="            ").rstrip("\n"))

    lines.append('        }')  # end Arm
    lines.append('    }')      # end Actors
    lines.append('')
    lines.append('    def Scope "Environment"')
    lines.append('    {')
    lines.append('        def Cylinder "Vessel" (')
    lines.append('            customData = {')
    lines.append('                string mimeRole = "physics_boundary"')
    lines.append('                string mimeBoundaryType = "bounce_back"')
    lines.append('            }')
    lines.append('        )')
    lines.append('        {')
    lines.append(f'            double height = {float(vessel_length_m)}')
    lines.append(f'            double radius = {float(vessel_radius_m)}')
    lines.append('            token axis = "Z"')
    lines.append('            double3 xformOp:translate = (0, 0, 0)')
    lines.append('            uniform token[] xformOpOrder = ["xformOp:translate"]')
    lines.append('        }')
    lines.append('    }')
    lines.append('}')
    lines.append('')
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv=None) -> int:
    p = argparse.ArgumentParser(
        description=(
            "Author-time helper that derives a placeholder world.usda "
            "from a URDF (one Xform per link, tagged with mimeNodeName)."
        ),
    )
    p.add_argument("urdf_path", help="Path to input URDF file")
    p.add_argument(
        "--output", "-o", default="world.usda",
        help="Path to output .usda file (default: ./world.usda)",
    )
    p.add_argument(
        "--vessel-radius", type=float, default=0.0047,
        help="Default vessel radius [m] (default: 0.0047 — 1/4\" tubing)",
    )
    p.add_argument(
        "--vessel-length", type=float, default=0.02,
        help="Default vessel length [m] (default: 0.02)",
    )
    p.add_argument(
        "--arm-actor-prefix", default="arm_link_",
        help="Prefix for each link's mimeNodeName (default: arm_link_)",
    )
    args = p.parse_args(argv)

    if not os.path.exists(args.urdf_path):
        print(f"error: URDF not found: {args.urdf_path}", file=sys.stderr)
        return 1

    link_names = _parse_link_names(args.urdf_path)
    usda = emit_usda(
        link_names,
        vessel_radius_m=args.vessel_radius,
        vessel_length_m=args.vessel_length,
        arm_actor_prefix=args.arm_actor_prefix,
    )

    out_dir = os.path.dirname(os.path.abspath(args.output))
    if out_dir and not os.path.isdir(out_dir):
        os.makedirs(out_dir, exist_ok=True)

    with open(args.output, "w") as f:
        f.write(usda)

    print(f"wrote {args.output} ({len(link_names)} links)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
